FROM grafana/grafana

COPY ./monitor/grafana/provisioning/datasources /etc/grafana/provisioning/datasources
COPY ./monitor/grafana/provisioning/dashboards /etc/grafana/provisioning/dashboards

EXPOSE 3000