global:
  scrape_interval: 3s # By default, scrape targets every 5 seconds.

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
          - localhost:9090
  - job_name: 'rabbitmq'
    static_configs:
      - targets:
          - rabbit-clusterip:15692
  - job_name: 'student'
    scheme: http
    static_configs:
      - targets:
          - student-clusterip
  - job_name: 'attendance'
    scheme: http
    static_configs:
      - targets:
          - attendance-clusterip
  - job_name: 'notify'
    scheme: http
    static_configs:
      - targets:
          - notify-clusterip
  - job_name: 'ow'
    scheme: http
    static_configs:
      - targets:
          - ow-clusterip