apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: realshinchoku/ddhc-prometheus
          ports:
            - containerPort: 9090
#      volumes:
#        - name: prometheus-config-volume
#          hostPath:
#            path: /monitor/prometheus/prometheus.yml
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-clusterip
spec:
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090