apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-svc
  labels:
    app: student-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-svc
  template:
    metadata:
      name: student-svc
      labels:
        app: student-svc
    spec:
      containers:
        - name: student-svc
          image: realshinchoku/ddhc-student-svc:latest
          imagePullPolicy: Always
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: connectionString
            - name: RabbitMQ__Host
              value: rabbit-clusterip
            - name: RabbitMQ__Username
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: username
            - name: RabbitMQ__Password
              valueFrom:
                secretKeyRef:
                  name: rabbit-secret
                  key: password
            - name: AzureAd__Instance
              value: https://login.microsoftonline.com/
            - name: AzureAd__TenantId
              value: TENANT_ID
            - name: AzureAd__ClientId
              valueFrom:
                secretKeyRef:
                  name: azure-secret
                  key: clientId
            - name: AzureAd__ClientSecret
              valueFrom:
                secretKeyRef:
                  name: azure-secret
                  key: clientSecret
            - name: AzureAd__Scopes
              value: SCOPES
            - name: DownstreamApi__BaseUrl
              value: https://graph.microsoft.com/v1.0
            - name: DownstreamApi__Scopes__0
              value: SCOPES
            - name: DownstreamApi__Scopes__1
              value: openid
            - name: DownstreamApi__Scopes__2
              value: profile
            - name: DownstreamApi__Scopes__3
              value: offline_access
            - name: DownstreamApi__Scopes__4
              value: email
            - name: CacheOption
              value: Redis
            - name: Redis__Host
              value: redis-clusterip
            - name: Redis__Port
              value: "6379"
            - name: Redis__SerializerName
              value: Pack
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: student-clusterip
spec:
  type: ClusterIP
  selector:
    app: student-svc
  ports:
    - port: 80
      targetPort: 80
      name: web