apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-client
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: teacher-client
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: teacher-client
    spec:
      containers:
        - image: realshinchoku/ddhc-teacher-client
          imagePullPolicy: Always
          name: teacher-client
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: teacher-client
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: teacher-client