apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  password: "postgresSecretPw"
  connectionString: "Server=postgres-clusterip:5432;User Id=postgres;Password=postgresSecretPw;Database=InfoStudent"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbit-secret
type: Opaque
stringData:
  username: "rabbitUn"
  password: "rabbitSecretPw"
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  username: "mongoUn"
  password: "mongoSecretPw"
  connectionString: "mongodb://mongoUn:mongoSecretPw@mongo-clusterip"
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-secret
type: Opaque
stringData:
  clientSecret: "CLIENT_SECRET"
  clientId: "CLIENT_ID"

