name: build-prometheus

on:
  workflow_dispatch:
  push:
    paths:
      - 'monitor/prometheus/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}"
          file: ./monitor/prometheus/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ddhc-prometheus